### PR TITLE
add function for setting table name

### PR DESCRIPTION
**Pull request by teros0**
and add godoc icon for quicker documentation access

### CODE REVIEW

**Comment by wrunk** [comment]
Perhaps we can make this work like PGC: https://github.com/cliqueinc/pgc/blob/master/parse.go#L255

**Comment by teros0** [comment]
Upon closer inspection, I've found such function in mwear, setTableName.
What do you think about making func that setTableName looks for, TableName, unexported, something like mwearTableName? I think that it shouldn't be available as part of struct public API.

**Comment by wrunk** [comment]
It would be better if it were not exported, but would reflect be able to then call that function from a different package (mysql-wear)?

**Comment by teros0** [comment]
Yup, looked it up, there is no way to call unexported method, even through reflection.
Closing this PR.

**Pull request closed without merging**
